version: "3"

services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
      - DB_URL=postgresql+psycopg2://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
  redis:
    container_name: "redis"
    image: redis:alpine
    ports:
      - "6379:6379"
  web:
    restart: unless-stopped
    build: ./app
    command:
      bash -c "sleep 10 && cd app && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "5555:5555"
    environment:
      - DB_URL=postgresql+psycopg2://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
  celery:
    restart: unless-stopped
    build: ./app
    container_name: "celery"
    environment:
      - DB_URL=postgresql+psycopg2://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/code
    command: bash -c "cd app && celery -A task worker -B -l info"
    links:
      - redis
      - web

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
      - DB_URL=postgresql+psycopg2://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "5050:80"
    depends_on:
      - db


